[package]
name = "web3_hd"
version = "0.1.0"
edition = "2021"
authors = ["Nazgull08 <nazgull08@gmail.com>"]
description = "web3_hd is a library for working with the hierarchical deterministic web3 wallets"
license = "Apache-2.0"
repository = "https://github.com/nazgull08/web3-hd"
keywords = ["web3", "wallet", "hd"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "web3_hd"
path = "src/lib.rs"

[features]
default = ["nacl"]
nacl=["dep:nacl"]

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
ureq = "2.4.0"
anyhow = "1.0.57"
crc = "3.0.0"
byteorder = "1.4.3"
data-encoding = "2.3.2"
nacl = {version="0.5.3", optional=true}
rand = "0.8.4"
toml = "0.5.9"
regex = "1.5.6"
ed25519-dalek = "1.0.1"
digest = "0.8.0"
